import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Avatar, AvatarFallback, AvatarImage } from '../components/ui/avatar'
import { Sidebar } from './Components/Sidebar'
import Image from 'next/image'
import Link from 'next/link'
import logo2 from '../../public/logo2.jpeg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // NAV BAR
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container mx-auto ">
            <Link href="/">
             <Image src={logo2} alt="logo" className=' w-48' />
            </Link>
          
            <div className='ml-auto flex items-center px-4 container mx-auto'></div>
            <Avatar>
              <AvatarImage src="https://github.com/shadcn.png" />
              <AvatarFallback>JH</AvatarFallback>
            </Avatar>
          </div>
        </div>
        <div className='flex'>
          <Sidebar/>        
          <div className="w-full px-10">{children}</div>
        </div>
      </body>
    </html>
  )
}
